name:                piped
version:             0.1.0.0
github:              "githubuser/piped"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Conduit with a smaller core
category:            Control

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/piped#readme>

dependencies:
- base >= 4.7 && < 5
- mtl

library:
  source-dirs: src

executables:
  piped-bench:
    main:                Bench.hs
    source-dirs:
    - test-bench
    - test-common
    when:
    - condition: (flag(bench))
      then:
        buildable: true
      else:
        buildable: false
    ghc-options:
    - -rtsopts
    - -O2
    - -fprof-auto
    - -fwarn-unused-imports
    dependencies:
    - piped
    - conduit
    - mtl
    - gauge
    - bench-show
    - split
    default-extensions:
    - LambdaCase
    - FlexibleContexts

tests:
  piped-test:
    main:                Discover.hs
    source-dirs:
    - test
    - test-common
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwarn-unused-imports
    dependencies:
    - piped
    - tasty
    - tasty-hunit
    - tasty-discover
    - tasty-golden
    - tasty-quickcheck
    - quickcheck-instances
    - conduit
    - microlens-platform
    default-extensions:
    - RankNTypes
    - MultiParamTypeClasses
    - FunctionalDependencies
    - FlexibleInstances
    - ConstraintKinds
    - TypeSynonymInstances
    - AllowAmbiguousTypes
    - LambdaCase
    - FlexibleContexts

flags:
  bench:
    description: Enable build benchmark
    manual: true
    default: false
