name:                piped-conduit
version:             0.1.0.0
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

description:         Conduit adapter for Piped

dependencies:
- base >= 4.7 && < 5
- piped
- conduit

library:
  source-dirs: src
